### ISSUE TITLE
Demo app crashes

### ISSUE THREAD

**Issue by chrisortman** [hotwired/turbo-android#146]
Hi, the demo app (when pointing to turbo-native-demo.glitch.me)  is crashing for me. I *think* it is because of the favicon returning a 404

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dev.hotwire.turbo.demo, PID: 29464
    java.lang.IllegalArgumentException: reasonPhrase can't be empty.
        at android.webkit.WebResourceResponse.setStatusCodeAndReasonPhrase(WebResourceResponse.java:138)
        at android.webkit.WebResourceResponse.<init>(WebResourceResponse.java:76)
        at xq.a(SourceFile:292)
        at alW.handleMessage(SourceFile:67)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6983)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
Disconnected from the target VM, address: 'localhost:61257', transport: 'socket'
```

This is a physical device (Samsung J7)
It does work on a pixel 2 simulator.

**Comment by chrisortman** [comment]
I wonder if this is related to Chrome < 70 ?
I wanted to compare relative performance with Hey app, and when I installed that it told me to update chrome.
After the chrome update, the favicon issue is fixed.

**Comment by chrisortman** [comment]
This can be closed as far as I'm concerned.

**Comment by jayohms** [comment]
Ah yes, old versions of `WebView` might be problematic. Version 70 was released over two years ago, so that should be pretty rare to see on a device. In our apps, we check the `session.webView.majorVersion` and prompt to upgrade if `WebView` is too old. That prompt is not included as part of the library, since it should feel like part of your app and in a place that makes sense.

**Comment by chriskroon** [comment]
Hey, this is still an issue to this date.
Whenever a user uninstalls (or deinstall updates of Google Chrome because they can't deinstall the app) Turbo doesn't work cause of webkit. 

What packages need to be installed whenever the user doesn't want to use Google Chrome?

**Comment by jayohms** [comment]
@chriskroon Here's the helper class we use in our apps. The user will either need to have the latest version of [Chrome](https://play.google.com/store/apps/details?id=com.android.chrome) or [Android System WebView](https://play.google.com/store/apps/details?id=com.google.android.webview) installed on their device, depending on their OS version.

You'll need to make the appropriate changes for the text/dialog/ui that makes sense in your app.

**WebViewHelper.kt**
```kotlin 
// WebView 89 released March 2021
const val MINIMUM_WEBVIEW_VERSION = 89
private const val PACKAGE_SYSTEM_WEBVIEW = "com.google.android.webview"
private const val PACKAGE_CHROME_WEBVIEW = "com.android.chrome"
private const val PACKAGE_CHROME_PRE_RELEASE_WEBVIEW = "com.chrome"

enum class WebViewType {
    ANDROID_SYSTEM,
    CHROME
}

class WebViewHelper {
    fun isWebViewOutdated(session: TurboSession): Boolean {
        val version = session.webViewVersion() ?: return false
        return version < MINIMUM_WEBVIEW_VERSION
    }

    fun showUpdateWebViewDialog(context: Context, session: TurboSession) {
        val webViewType = session.webViewType() ?: WebViewType.ANDROID_SYSTEM
        val version = session.webViewVersion() ?: -1

        val binding = DialogSystemInfoBinding.inflate(context.layoutInflater())
        val title = context.getString(R.string.system_update_dialog_title)
        val description = when (webViewType) {
            WebViewType.ANDROID_SYSTEM -> context.getString(R.string.error_system_webview_description)
            WebViewType.CHROME -> context.getString(R.string.error_chrome_webview_description)
        }.format(version, MINIMUM_WEBVIEW_VERSION)

        binding.title.text = title
        binding.description.text = description.fromHtml()

        MaterialAlertDialogBuilder(context).apply {
            setView(binding.root)
            setPositiveButton(R.string.system_update_dialog_button) { _, _ ->
                try {
                    val playStoreUri = playStoreUpdateUri(webViewType)
                    context.startActivity(Intent(Intent.ACTION_VIEW, playStoreUri))
                } catch (e: ActivityNotFoundException) {
                    Toast.makeText(context, "Play Store app is not available", Toast.LENGTH_LONG).show()
                }
            }
        }.create().show()
    }

    private fun TurboSession.webViewType(): WebViewType? {
        return when {
            webView.packageName?.contains(PACKAGE_CHROME_WEBVIEW) == true -> WebViewType.CHROME
            webView.packageName?.contains(PACKAGE_CHROME_PRE_RELEASE_WEBVIEW) == true -> WebViewType.CHROME
            webView.packageName?.contains(PACKAGE_SYSTEM_WEBVIEW) == true -> WebViewType.ANDROID_SYSTEM
            else -> null
        }
    }

    private fun TurboSession.webViewVersion(): Int? {
        return webView.majorVersion
    }

    fun getWebViewTypeName(session: TurboSession): String {
        return session.webViewType()?.toString() ?: "Unknown"
    }

    fun getWebViewVersionName(session: TurboSession): Int {
        return session.webViewVersion() ?: 0
    }

    private fun playStoreUpdateUri(type: WebViewType): Uri {
        return when (type) {
            WebViewType.ANDROID_SYSTEM -> Uri.parse("market://details?id=$PACKAGE_SYSTEM_WEBVIEW")
            WebViewType.CHROME -> Uri.parse("market://details?id=$PACKAGE_CHROME_WEBVIEW")
        }
    }
}
```
**strings.xml**
```xml
<!-- System compatibility -->
<string name="error_system_webview_description">The <![CDATA[<b>Android System WebView v%d</b>]]> app on your device, provided by Google, is outdated. <![CDATA[<b>Basecamp needs v%d</b>]]> to work properly, and you can easily update in the Play Store.</string>
<string name="error_chrome_webview_description">The <![CDATA[<b>Google Chrome v%d</b>]]> app on your device is outdated. <![CDATA[<b>Basecamp needs v%d</b>]]> to work properly, and you can easily update in the Play Store.</string>
<string name="system_update_dialog_button">Update in Play Store</string>
<string name="system_update_dialog_title">Basecamp requires an update</string>
```

**Comment by chriskroon** [comment]
Hey Jayohms,

Thanks for this help! I will build this in next Monday.

I think this might be implemented into the Turbo framework, can you fork it?

Cheers,
Chris
