### ISSUE TITLE
ClearBackStack is crashing when any modal is open inside webView

### ISSUE THREAD

**Issue by KarishmaAlignable** [hotwired/turbo-android#260]
When i am cleringBackStack normally it works correctly. but if in any webView a modal/dialog is open and then i clear back stack on click of a button it crashes with below error
`java.lang.IndexOutOfBoundsException: getChildDrawingOrder() returned invalid index 1 (child count is 1)
                                                                                                    	at android.view.ViewGroup.getAndVerifyPreorderedIndex(ViewGroup.java:2125)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4299)
                                                                                                    	at android.view.View.draw(View.java:22538)
                                                                                                    	at android.view.View.draw(View.java:22396)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
                                                                                                    	at android.view.View.draw(View.java:22394)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
                                                                                                    	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
                                                                                                    	at android.view.View.draw(View.java:22394)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
                                                                                                    	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:222)
                                                                                                    	at android.view.View.draw(View.java:22394)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
                                                                                                    	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
                                                                                                    	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
                                                                                                    	at android.view.View.draw(View.java:22394)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
                                                                                                    	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
                                                                                                    	at android.view.View.draw(View.java:22394)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
                                                                                                    	at android.view.View.draw(View.java:22394)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
                                                                                                    	at android.view.View.draw(View.java:22394)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
                                                                                                    	at android.view.View.draw(View.java:22394)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
                                                                                                    	at android.view.View.draw(View.java:22394)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
                                                                                                    	at android.view.View.draw(View.java:22538)
                                                                                                    	at com.android.internal.policy.DecorView.draw(DecorView.java:848)
                                                                                                    	at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:4542)
                                                                                                    	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4445)
                                                                                                    	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4144)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3391)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2182)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8730)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:1049)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:233)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8010)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)`

**Comment by KarishmaAlignable** [comment]
Below is my clearBackStackCode
`  fun clearBackStack(onCleared: () -> Unit = {}) {
        if (navController.previousBackStackEntry == null) {
            onCleared()
            return
        }
        while (navController.backQueue.size > 2) {
            navController.popBackStack()
            Log.d("poping_stack", "stack size ::" + navController.backQueue.size)
        }
        onCleared()
}`
